// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiverCliStorm.TelegramBot.Infrastructer;

#nullable disable

namespace ReceiverCliStorm.TelegramBot.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251213192015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.DeviceAuthInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("DeviceAuthInfo", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Exists");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionInfoId");

                    b.HasIndex("UserId");

                    b.HasIndex("CountryCode", "Number")
                        .IsUnique();

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.SessionInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionInfo", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.Settings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseChangeBio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCheckReport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLogCLI")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseProxy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.Sudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("En");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("Sudo", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPermissionToUse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("En");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.UserStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpierDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("UserStep", (string)null);
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.DeviceAuthInfo", b =>
                {
                    b.HasOne("ReceiverCliStorm.TelegramBot.Core.Domain.Session", null)
                        .WithOne("DeviceAuthInfo")
                        .HasForeignKey("ReceiverCliStorm.TelegramBot.Core.Domain.DeviceAuthInfo", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.Session", b =>
                {
                    b.HasOne("ReceiverCliStorm.TelegramBot.Core.Domain.SessionInfo", "SessionInfo")
                        .WithMany()
                        .HasForeignKey("SessionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceiverCliStorm.TelegramBot.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiverCliStorm.TelegramBot.Core.Domain.Session", b =>
                {
                    b.Navigation("DeviceAuthInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
